export default async function Head() {
  return (
    <>
      <title>이소림-웹 프론트엔드</title>
      <meta name="description" content="Generated by head" />
      <link
        rel="icon"
        href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🌳</text></svg>"
      />
    </>
  );
}
